stages:
  - build-container
  - deploy

variables:
  REPO_NAME: gitlab.com/$CI_PROJECT_PATH
  DOCKER_IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH
  TAG: $CI_COMMIT_SHORT_SHA

build-container:
  stage: build-container
  image: docker:19
  services:
    - docker:19-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE_TAG:$CI_COMMIT_SHORT_SHA -f Dockerfile .
    - docker tag $DOCKER_IMAGE_TAG:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE_TAG:latest
    - docker push $DOCKER_IMAGE_TAG
    - docker push $DOCKER_IMAGE_TAG:latest
    - docker logout $CI_REGISTRY
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: "$CI_COMMIT_BRANCH =~ /^(test)+/"

deploy:
  stage: deploy
  trigger:
    project: cjtim/my-server
    strategy: depend
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: "$CI_COMMIT_BRANCH =~ /^(test)+/"
